name: DeathSwap
version: '${version}'
main: me.ultradev.deathswap.Main
api-version: 1.16
commands:
  ds-start:
    permission: deathswap.commands.ds-start
  ds-end:
    permission: deathswap.commands.ds-end